# Generated by Django 4.1.4 on 2022-12-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_fee_amount', models.FloatField(default=0.0)),
                ('pay_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment_user.paymentuser')),
            ],
            options={
                'db_table': 'expired_payment',
            },
        ),
    ]
